# fcom v0.1

mod "core.globop"

mod_conf "core.file-in" {
	bufsize 64k
	nbufs 3
	direct_io true
	readahead true
}

mod_conf "core.file-out" {
	bufsize 64k

	# Preallocate disk space if output file size is unknown
	prealloc 1m

	# Increase prealloc value when needed
	prealloc_grow true

	# Create directories for a new file when needed
	mkpath true

	# Delete file on error
	del_on_err true
}

mod "core.f-touch"

mod "arc.unxz"
