# fcom v0.4

mod_conf "core.file-in" {
	bufsize 64k
	nbufs 3
	direct_io true
	readahead true
}

mod_conf "core.file-out" {
	bufsize 64k

	# Preallocate disk space if output file size is unknown
	prealloc 1m

	# Increase prealloc value when needed
	prealloc_grow true

	# Create directories for a new file when needed
	mkpath true

	# Delete file on error
	del_on_err true
}

mod "core.dir-out"
mod "core.stdin"
mod "core.stdout"

mod "file.touch"
mod "file.textcount"
mod "file.crc"
mod "file.wregfind"

mod "fsync.sync"
mod "fsync.syncss"
mod "fsync.fsync"

mod "arc.gz"
mod "arc.ungz"
mod "arc.ungz1"
mod "arc.unxz"
mod "arc.unxz1"
mod "arc.tar"
mod "arc.untar"
mod "arc.zip"
mod "arc.unzip"
mod "arc.un7z"
mod "arc.uniso"
mod "arc.unpack"

mod "pic.conv"
mod "pic.pxconv"
mod "pic.bmp-in"
mod "pic.bmp-out"
mod "pic.jpg-in"

mod_conf "pic.jpg-out" {
	quality 90
}

mod "pic.png-in"

mod_conf "pic.png-out" {
	compression 9
}

mod "gui.gui"
mod "gui.dcbmp"
