# fcom v0.14 configuration

# Code page for non-Unicode data: win866 win1251 win1252
codepage win1252

# Maximum worker threads
# 0: use all CPUs
workers 0

mod_conf "core.file-in" {
	bufsize 64k
	nbufs 3
	readahead true

	# Offload read operations to another thread
	# Usually, asynchronous reading isn't needed because CPU hasn't got any work
	use_thread_pool false

	# Read from file using the system's asynchronous I/O
	direct_io false
}

mod_conf "core.file-out" {
	bufsize 64k

	# Preallocate disk space if output file size is unknown
	prealloc 1m

	# Increase prealloc value when needed
	prealloc_grow true

	# Create directories for a new file when needed
	mkpath true

	# Delete file on error
	del_on_err true

	# Offload write operations to another thread
	# Asynchronous writing may help utilizing more CPU resources
	use_thread_pool true
}

mod "core.dir-out"
mod "core.stdin"
mod "core.stdout"

mod "file.ops"
mod "file.copy"
mod "file.touch"
mod "file.rename"
mod "file.textcount"
mod "file.utf8"
mod "file.crc"
mod "file.wregfind"
mod "file.pe"
mod "file.disk"
mod "file.mount"
mod "file.hexprint"

mod "crypto.crypt"
mod "crypto.encrypt1"
mod "crypto.decrypt1"

mod "fsync.sync"
mod "fsync.syncss"
mod "fsync.fsync"

mod "arc.zstd1"
mod "arc.unzstd1"
mod "arc.zst"
mod "arc.unzst"
mod "arc.gz"
mod "arc.gz1"
mod "arc.ungz"
mod "arc.ungz1"
mod "arc.unxz"
mod "arc.unxz1"
mod "arc.tar"
mod "arc.untar"
mod "arc.untar1"
mod "arc.zip"
mod "arc.unzip"
mod "arc.unzip1"
mod "arc.un7z"
mod "arc.iso"
mod "arc.uniso"
mod "arc.unpack"
mod "arc.ico-in"

mod "pic.conv"
mod "pic.pxconv"
mod "pic.crop"
mod "pic.bmp-in"
mod "pic.bmp-out"
mod "pic.jpg-in"

mod_conf "pic.jpg-out" {
	quality 90
}

mod "pic.png-in"

mod_conf "pic.png-out" {
	compression 9
}

mod "net.dnscl"

mod "gui.gui"
mod "gui.dcbmp"
